### ISSUE TITLE
Update the script to Python 3

### ISSUE THREAD

**Issue by anuveyatsu** [datasets/ppp#13]
Currently, it runs/tested on Python 2 which is now outdated. We'd like to run it using Python 3.

## Acceptance

- [x] The script runs on Python 3 https://github.com/datasets/ppp/tree/master/scripts

## Tasks

- [x] Update the script and if needed update the list of requirements
- [ ] Update the README

**Comment by Gutts-n** [comment]
@anuveyatsu hey, I fixed the issue but I can't push from my local branch and I also can't create branches using the GitHub UI, can you help me? 

```bash
git push --set-upstream origin feature/python3-upgrade

ERROR: Permission to datasets/ppp.git denied to Gutts-n.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I'm Leo, I was recommended by @demenech.

**Comment by anuveyatsu** [comment]
Hi @Gutts-n thanks for reaching out! I think you'd normally create your own fork of a repository and then create a pull request. That workflow is the simplest and doesn't require giving additional permissions to a contributor. Would you mind doing that way?

**Comment by Gutts-n** [comment]
I created the PR, here it is https://github.com/datasets/ppp/pull/16.

**Comment by anuveyatsu** [comment]
Closing this as FIXED. The data pipelines are running on a monthly basis.
